### ISSUE TITLE
HTTP 409: Conflict error when trying to deploy

### ISSUE THREAD

**Issue by reverie** [twilio/twilio-video-app-react#128]
**Describe the bug**
I followed the steps up through `npm run deploy:twilio-cli`, which failed with a 409 Conflict http error. CRA built successfully, then the console printed:
-`Something went wrong GotError [HTTPError]: Response code 409 (CONFLICT)`
- a log of the HTTP response object, including `statusCode` 409
- `deploying app...`
- error output including: npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build

Running the deploy command subsequent times does not display anything about an HTTP error, it just says
 `» twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues` after the CRA build.

**Environment (please complete the following information):**
 - OS: macOS Catalina
 - App Version: master/02a648baf7506868ae3c3896a8ca0648c2dd8943
 - Node.js version: v12.14.0

**Comment by timmydoza** [comment]
Thanks for the issue @reverie!

We could take a closer look at the issue with some logs. If you run `npm run deploy:twilio-cli -- -l debug`, what does it print to the console? This may help us figure out which specific http request is getting the 409.

**Comment by reverie** [comment]
@timmydoza Not getting the 409 anymore, but here's the debug output:

```
andrew@hazel ~/tmp/twilio-video-app-react
: npm run deploy:twilio-cli -- -l debug

> twilio-video-app-react@0.1.0 deploy:twilio-cli /Users/andrew/tmp/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "-l" "debug"


> twilio-video-app-react@0.1.0 build /Users/andrew/tmp/twilio-video-app-react
> react-scripts build

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  262.17 KB  build/static/js/2.4dd8aa1f.chunk.js
  11.82 KB   build/static/js/main.62cb6256.chunk.js
  784 B      build/static/js/runtime-main.fa60846a.js

The project was built assuming it is hosted at /.
You can control this with the homepage field in your package.json.

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  bit.ly/CRA-deploy

[DEBUG] Config File: /Users/andrew/.twilio-cli/config.json
[DEBUG] Using profile: mixily
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.42.0, node.js v12.14.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 03 Apr 2020 21:11:43 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ9080e36bad174821aee75d708d1e5c20","twilio-request-duration":"0.052","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS1160f95f212d8f135bdc082519cee697/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.42.0, node.js v12.14.0, darwin 19.3.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Fri, 03 Apr 2020 21:11:43 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ4d913d81e86e4afa99596e7524ea465e","twilio-request-duration":"0.029","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/andrew/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:76:64)
    at processTicksAndRejections (internal/process/task_queues.js:93:5)
    at async DeployCommand.run (/Users/andrew/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/Users/andrew/.twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "-l" "debug"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/andrew/.npm/_logs/2020-04-03T21_11_43_524Z-debug.log
```

**Comment by timmydoza** [comment]
Thanks for the logs @reverie!

We found that sometimes the CLI plugin can get into a weird state - so we released a new version of the plugin that should help with this.

Can you please try the steps outlines in the [Troubleshooting the Twilio CLI](https://github.com/twilio/twilio-video-app-react#troubleshooting-the-twilio-cli) section of the readme and let me know if it solves your issue?

**Comment by reverie** [comment]
@timmydoza That worked, thanks! Got my test app deployed.

**Comment by timmydoza** [comment]
Glad it worked! Please let me know if you see any further issues. Thanks!
