### ISSUE TITLE
Unable to deploy react app

### ISSUE THREAD

**Issue by Balasnest** [twilio/twilio-video-app-react#200]
**Describe the bug**
I have logged in and added SID, Auth token also. But unable to deploy to production.

> twilio rtc:apps:video:deploy --authentication passcode -l debug

```
[DEBUG] Config File: /Users/bala/.twilio-cli/config.json
[DEBUG] Using profile: multiGuy
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.0, node.js v10.16.1, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 11 May 2020 05:56:25 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ8134a0a5fe0a400295e5ac39af1aad42","twilio-request-duration":"0.018","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZS89df49b7b8dbf76094ca57315cc4bbc0/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.43.0, node.js v10.16.1, darwin 18.7.0 x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 11 May 2020 05:56:26 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ37cb8e797c964af0bdbde27ef91d08b0","twilio-request-duration":"0.016","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/bala/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

**Environment (please complete the following information):**
 - OS: [macOS 10.14.6]
 - Browser: [Chrome 81, Chromium 84]
 - App Version: [0.1.0]
 - SDK Version: [^2.4.0]
 - Node.js version: [10.16.1]

**Comment by timmydoza** [comment]
Thanks for the question @Balasnest!

Our readme has some steps to try in the "Troubleshooting the Twilio CLI" section:

https://github.com/twilio/twilio-video-app-react#troubleshooting-the-twilio-cli

Can you try those steps and let me know if you still see the error? Thanks!!

**Comment by timmydoza** [comment]
Closing due to inactivity. Please let mw know if you still encounter problems!
