### ISSUE TITLE
error when trying to deploy

### ISSUE THREAD

**Issue by tomeraz** [twilio/twilio-video-app-react#237]
**Describe the bug**
error when trying to deploy

**To Reproduce**
1. Run npm run deploy:twilio-cli -- -l debug

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04
 - Node.js version: v12.16.3

**Additional context**
Here's the debug output:
```
➜  twilio-video-app-react git:(master) npm run deploy:twilio-cli -- -l debug      

> twilio-video-app-react@0.1.0 deploy:twilio-cli /home/tomeraz/playground/twilio/twilio-video-app-react
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "-l" "debug"


> twilio-video-app-react@0.1.0 build /home/tomeraz/playground/twilio/twilio-video-app-react
> node ./scripts/build.js

Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  267.19 KB  build/static/js/2.46890bb3.chunk.js
  15.73 KB   build/static/js/main.441bee3c.chunk.js
  784 B      build/static/js/runtime-main.fa60846a.js

[DEBUG] Config File: /home/tomeraz/.twilio-cli/config.json
[DEBUG] Using profile: tomeraz
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.45.0, node.js v12.16.3, linux 5.3.0-51-generic x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 08 Jun 2020 21:34:52 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"1067","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ8d034eac675b402c93b8a281fbdb6f0d","twilio-request-duration":"0.048","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
[DEBUG] -- BEGIN Twilio API Request --
[DEBUG] GET https://serverless.twilio.com/v1/Services/ZSe7d4c61f4b3c412dc64e14076d3a3f45/Environments
[DEBUG] User-Agent: @twilio/cli-core/4.6.0 (twilio-node/3.45.0, node.js v12.16.3, linux 5.3.0-51-generic x64, rtc:apps:video:deploy)
[DEBUG] -- END Twilio API Request --
[DEBUG] response.statusCode: 200
[DEBUG] response.headers: {"date":"Mon, 08 Jun 2020 21:34:53 GMT","content-type":"application/json; charset=utf-8; charset=utf-8","content-length":"380","connection":"close","twilio-concurrent-requests":"1","twilio-request-id":"RQ4a86a77444da4c6e8d8ce23ffc63fb88","twilio-request-duration":"0.023","access-control-allow-origin":"*","access-control-allow-headers":"Accept, Authorization, Content-Type, If-Match, If-Modified-Since, If-None-Match, If-Unmodified-Since","access-control-allow-methods":"GET, POST, DELETE, OPTIONS","access-control-expose-headers":"ETag","access-control-allow-credentials":"true","x-powered-by":"AT-5000","x-shenanigans":"none","x-home-region":"us1","x-api-domain":"serverless.twilio.com","strict-transport-security":"max-age=31536000"}
 » twilio-cli encountered an unexpected error. To report this issue, execute the command with the "-l debug" flag, then copy the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/home/tomeraz/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:77:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/home/tomeraz/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:20)
    at async DeployCommand._run (/home/tomeraz/.twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
    at async Config.runCommand (/home/tomeraz/.npm/lib/node_modules/twilio-cli/node_modules/@oclif/config/lib/config.js:172:9)
    at async Main.run (/home/tomeraz/.npm/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/main.js:22:9)
    at async Main._run (/home/tomeraz/.npm/lib/node_modules/twilio-cli/node_modules/@oclif/command/lib/command.js:43:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "-l" "debug"`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/tomeraz/.npm/_logs/2020-06-08T21_34_53_930Z-debug.log

```

**Comment by timmydoza** [comment]
Thanks for the issue @tomeraz!

I'm curious, did you encounter this error on your very first attempt at running `npm run deploy:twilio-cli`? Or did you previously try to deploy the app? I'm trying to figure out what could cause this issue so we can fix it. 

As a workaround, can you please try the steps in our [Troubleshooting the Twilio CLI](https://github.com/twilio/twilio-video-app-react#troubleshooting-the-twilio-cli) section of our readme? I think it will solve your issue.

Thanks!
