### ISSUE TITLE
Fetching Could not find profile "undefined" error when I do npm run deploy:twilio-cli

### ISSUE THREAD

**Issue by saad4s** [twilio/twilio-video-app-react#243]
When I do `npm run deploy:twilio-cli`, it will raise the Could not find profile "undefined" error like below
```
> twilio-video-app-react@0.1.0 deploy:twilio-cli /root/twilio/video-call
> cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build

> twilio-video-app-react@0.1.0 build /root/twilio/video-call
> node ./scripts/build.js

Creating an optimized production build...
 » Could not find profile "undefined".
 » To create the profile, run:

  twilio profiles:create

Alternatively, twilio-cli can use credentials stored in environment variables:

# OPTION 1 (recommended)
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_API_KEY = an API Key created at twil.io/get-api-key
TWILIO_API_SECRET = the secret for the API Key

# OPTION 2
TWILIO_ACCOUNT_SID = your Account SID from twil.io/console
TWILIO_AUTH_TOKEN = your Auth Token from twil.io/console

Once these environment variables are set, a twilio-cli profile is not required to move forward with installation.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2020-06-14T16_34_34_473Z-debug.log
```

### Complete log of this run
```
0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   '/root/.nvm/versions/node/v12.18.0/bin/node',
1 verbose cli   '/root/.nvm/versions/node/v12.18.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'deploy:twilio-cli'
1 verbose cli ]
2 info using npm@6.14.5
3 info using node@v12.18.0
4 verbose run-script [
4 verbose run-script   'predeploy:twilio-cli',
4 verbose run-script   'deploy:twilio-cli',
4 verbose run-script   'postdeploy:twilio-cli'
4 verbose run-script ]
5 info lifecycle twilio-video-app-react@0.1.0~predeploy:twilio-cli: twilio-video-app-react@0.1.0
6 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: twilio-video-app-react@0.1.0
7 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: unsafe-perm in lifecycle true
8 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: PATH: /root/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/root/twilio/video-call/node_modules/.bin:/root/.nvm/versions/node/v12.18.0/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
9 verbose lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: CWD: /root/twilio/video-call
10 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build'
10 silly lifecycle ]
11 silly lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Returned: code: 1  signal: null
12 info lifecycle twilio-video-app-react@0.1.0~deploy:twilio-cli: Failed to exec deploy:twilio-cli script
13 verbose stack Error: twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/root/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (/root/.nvm/versions/node/v12.18.0/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid twilio-video-app-react@0.1.0
15 verbose cwd /root/twilio/video-call
16 verbose Linux 4.15.0-66-generic
17 verbose argv "/root/.nvm/versions/node/v12.18.0/bin/node" "/root/.nvm/versions/node/v12.18.0/bin/npm" "run" "deploy:twilio-cli"
18 verbose node v12.18.0
19 verbose npm  v6.14.5
20 error code ELIFECYCLE
21 error errno 1
22 error twilio-video-app-react@0.1.0 deploy:twilio-cli: `cross-env REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build`
22 error Exit status 1
23 error Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**I stored TWILIO_ACCOUNT_SID, TWILIO_API_KEY_SID and TWILIO_API_KEY_SECRET in a .env file. I tell Git to ignore the .env file by adding *.env to my .gitignore file.** 
**_Additionaly:_** `npm install -g twilio-cli` not working. I do `npm install twilio-cli@2.3.0` instead of `npm install -g twilio-cli` and also `twilio login` not working.

In the other hand, if I do `npm run build` then it works. After moving all files and folders to hosting directory it is running. But when I try to join it shows an error. 
### Screenshot of Error
![image](https://user-images.githubusercontent.com/17269909/84599976-c8c6fc00-ae97-11ea-8081-ef347e9032ea.png)

**Environment:**
 - Digitalocean droplet
 - OS: Ubuntu 18.04
 - Twilio-Cli Version: 2.3.0
 - NPM Version: 6.14.5
 - Node.js version: v12.18.0

**Comment by timmydoza** [comment]
Thanks for the issue @saad4s!

Sorry to hear that you are having trouble. When you say that `npm install -g twilio-cli` isn't working, is it giving you any errors? Please list any errors here so that we can help you diagnose the issue. The first error you encounter `Could not find profile "undefined"` indicates that the Twilio CLI was installed correctly.  What happens when you run `twilio -v`?

Have you run `twilio login`? Are any profiles listed when you run `twilio profiles:list`?

The error that you see in the browser indicates that you may not be running a server that dispenses video access tokens. Can you look in the network pane of the browser's development tools and see if there is an error when the app tries to make a request to `/token`? If so what error is it?

 In order to better assist you with running the app on Digital Ocean, I'll need more information on how you are deploying your app, what commands you are running, and what environment your are using. 

Thanks!

**Comment by timmydoza** [comment]
Closing due to inactivity. Happy to reopen with more information!
