### ISSUE TITLE
Cannot find module '@oclif/command'

### ISSUE THREAD

**Issue by mominnawaf** [twilio/twilio-video-app-react#274]
when i run `twilio login`
I get error as 

Error: Cannot find module '@oclif/command'
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
    at Function.Module._load (internal/modules/cjs/loader.js:562:25)
    at Module.require (internal/modules/cjs/loader.js:690:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (C:\Users\Nawaf Momin\AppData\Roaming\npm\node_modules\twilio-cli\bin\run:4:17)
    at Module._compile (internal/modules/cjs/loader.js:776:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:787:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)`

**Comment by timmydoza** [comment]
Thanks for the question @mominnawaf!

Unfortunately, I cannot reproduce the issue myself. It's also difficult to know what the issue could be without more information. Can you please create a new issue and complete our issue template in full? The more we know about your environment, what commands you have run, what exact steps are required to reproduce the issue, etc., the better we will be able to help you. 

Thanks!
