### ISSUE TITLE
Error when attempting to build local server

### ISSUE THREAD

**Issue by runnermann** [twilio/twilio-video-app-react#814]
**Describe the bug**

> npm start has an error and does not build the server. I receive this error: 
 Error: error:0308010C:digital envelope routines::unsupported  at new Hash (node:internal/crypto/hash:69:19)

**To Reproduce**

> 
1. Followed the instructions from readme.md
2. git clone https://github.com/twilio/twilio-video-app-react.git and cd into the directory
3. run npm install 
4. received many warnings with "high" vulnerabilities, thus updated according to node
5. Attempted with and without yarn install, but had same error
6. Did not add krisp, I attempted this but had many errors
7. installed twilio CLI
8. updated twilio CLI
9. twilio login
10. Ensure .env has correct TWILIO_ACCOUNT_SID, TWILIO_API_KEY_SK, TWILIO API_KEY_SECRET_TWILIO_CONVERSATIONS_SERVICE_SID
11. Set a new Conversatoins Service in the Services Sectoin
12. Attempt to run app locally with npm start

> RESULTS: ERROR in CLI: The default browser is launched with a black screen. 

> [dev] Error: error:0308010C:digital envelope routines::unsupported
[dev]     at new Hash (node:internal/crypto/hash:69:19)
[dev]     at Object.createHash (node:crypto:138:10)
[dev]     at module.exports (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/webpack/lib/util/createHash.js:90:53)
[dev]     at NormalModule._initBuildHash (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:386:16)
[dev]     at handleParseError (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:434:10)
[dev]     at /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:466:5
[dev]     at /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/webpack/lib/NormalModule.js:327:12
[dev]     at /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:373:3
[dev]     at iterateNormalLoaders (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
[dev]     at iterateNormalLoaders (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:221:10)
[dev]     at /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:236:3
[dev]     at runSyncOrAsync (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:130:11)
[dev]     at iterateNormalLoaders (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:232:2)
[dev]     at Array.<anonymous> (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/loader-runner/lib/LoaderRunner.js:205:4)
[dev]     at Storage.finished (/Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:55:16)
[dev]     at /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/node_modules/enhanced-resolve/lib/CachedInputFileSystem.js:91:9
[dev] /Users/ls/Twilio_React_Projects/SECOND/twilio-video-app-react/node_modules/react-scripts/scripts/start.js:19
[dev]   throw err;

**Expected behavior**
Should be able to build, launch, and run a local server for the video app

**Screenshots**

**Environment (please complete the following information):**
System details: Macbookpro intel i9, OSX 13.1
npm --version = 9.7.2
node --version = 20.3.1
browser = Chrome

**Additional context**
I was successful in building, launching and running a local server as well as deploying it in test mode to learn about Twilio Video. Worked great. I then attempted to modify the web page and app to customize it for our use. After than I could not get the server to run. I attempted to rebuild it from scratch with no success. Great instructions, and Twilio performed great. Thanks.

**Comment by runnermann** [comment]
Was able to successfully build and deploy the project in a new directory, but did NOT run npm audit fix --force

> 62 vulnerabilities (11 moderate, 51 high)
