### ISSUE TITLE
500 error on deploy during quick start

### ISSUE THREAD

**Issue by thedug** [twilio/twilio-video-app-react#90]
**Describe the bug**
I'm attempting to demo the twillio-video-app-react. I get a 500 on the deploy step.

**To Reproduce**
1) Install and configure the Twilio CLI.
2) Run twilio plugins:install @twilio-labs/plugin-rtc to install the app's support plugin.
3) Run npm run deploy:twilio-cli
4) 500 error...

**Expected behavior**
the process would exit with out errors and provide a link to view the app. 

**Screenshots**
N/A?

**Environment (please complete the following information):**
 - OS: OSX
 - Browser: N/A
 - App Version: Github Head
 - SDK Version: Github Head
 - Node.js version: 13.7

**Additional context**
N/A

**Comment by thedug** [comment]
Worked find on linux.

**Comment by timmydoza** [comment]
Thanks for the info @thedug! 

Unfortunately I'm unable to reproduce the issue that you are seeing. 

If you run `npm run deploy:twilio-cli -- -l debug`, it will try to build and deploy the app as usual, but it will also output lots of debug information to the console. Try running that command and see if there are any useful error messages that are printed, and feel free to paste them here if you'd like me to take a look.

**Comment by thedug** [comment]
the output to a new issue here: https://github.com/twilio/twilio-cli/issues
[DEBUG] Cannot read property 'sid' of undefined
[DEBUG] TypeError: Cannot read property 'sid' of undefined
    at DeployCommand.getAppInfo (/Users/thedug/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/helpers.js:74:64)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async DeployCommand.run (/Users/thedug/.twilio-cli/node_modules/@twilio-labs/plugin-rtc/src/commands/rtc/apps/video/deploy.js:18:21)
    at async DeployCommand._run (/Users/thedug/.twilio-cli/node_modules/@oclif/command/lib/command.js:44:20)
    at async Config.runCommand (/usr/local/Cellar/twilio/1.10.0/libexec/node_modules/@oclif/config/lib/config.js:160:9)
    at async Main.run (/usr/local/Cellar/twilio/1.10.0/libexec/node_modules/@oclif/command/lib/main.js:21:9)
    at async Main._run (/usr/local/Cellar/twilio/1.10.0/libexec/node_modules/@oclif/command/lib/command.js:44:20)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! twilio-video-app-react@0.1.0 deploy:twilio-cli: `REACT_APP_SET_AUTH=passcode npm run build && twilio rtc:apps:video:deploy --authentication=passcode --app-directory ./build "-l" "debug"`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the twilio-video-app-react@0.1.0 deploy:twilio-cli script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

**Comment by aaalaniz** [comment]
Hey @thedug 

Thank you for filing the issue. We are tracking this [issue in the Twilio CLI RTC plugin](https://github.com/twilio-labs/plugin-rtc/issues/16).

Thanks!
